### ISSUE TITLE
Came up in console

### ISSUE THREAD

**Issue by jrodr10** [SergeyDertan/SRegionProtector#10]
22:47:43 [FATAL] Could not pass event 'cn.nukkit.event.player.PlayerInteractEvent' to 'SRegionProtector v18.8': null on Sergey_Dertan.SRegionProtector.Event.RegionEventsHandler
22:47:43 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.block.BlockPressurePlateBase.onEntityCollide(BlockPressurePlateBase.java:129) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.checkBlockCollision(Player.java:1392) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1160) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:206) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.onUpdate(Player.java:1668) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.level.Level.doTick(Level.java:781) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.checkTickUpdates(Server.java:1036) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1117) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:886) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:863) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:554) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:98) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException
        at Sergey_Dertan.SRegionProtector.Event.RegionEventsHandler.playerInteract(RegionEventsHandler.java:154) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 14 more

**Comment by SergeyDertan** [comment]
fixed
