### ISSUE TITLE
Нельзя открыть форму, если класс игрока не стандартный.

### ISSUE THREAD

**Issue by Yexeed** [SergeyDertan/SRegionProtector#12]
У меня стоит античит GAC, который переписывает класс игрока, делая его NukkitCheatPlayer.class, и вот какая ошибка происходит при создании UIForm
```
13:13:35 [ERROR] Cannot create UIForm
java.lang.NoSuchMethodException: Sergey_Dertan.SRegionProtector.UI.Form.Type.MainForm.<init>(Sergey_Dertan.SRegionProtector.Region.Region, cz.creeperface.nukkit.gac.player.NukkitCheatPlayer)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_201]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_201]
	at Sergey_Dertan.SRegionProtector.UI.Form.Type.UIForm.getInstance(UIForm.java:21) ~[?:?]
	at Sergey_Dertan.SRegionProtector.UI.Form.FormUIManager.open(FormUIManager.java:19) ~[?:?]
	at Sergey_Dertan.SRegionProtector.Command.Manage.OpenUICommand.openGUI(OpenUICommand.java:77) ~[?:?]
	at Sergey_Dertan.SRegionProtector.Command.Manage.OpenUICommand.execute(OpenUICommand.java:57) ~[?:?]
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit.jar:?]
	at cn.nukkit.Server.dispatchCommand(Server.java:751) ~[nukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2721) ~[nukkit.jar:?]
	at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_201]
	at cn.nukkit.network.Network.processPackets(Network.java:185) [nukkit.jar:?]
	at cn.nukkit.network.Network.processBatch(Network.java:167) [nukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2072) [nukkit.jar:?]
	at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [nukkit.jar:?]
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [nukkit.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:76) [nukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1123) [nukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:903) [nukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:880) [nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:565) [nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?]
```

**Comment by SergeyDertan** [comment]
Можешь использовать инвентарь сундука(chest ui в конфиге)
Ошибку проверю

**Comment by SergeyDertan** [comment]
Без GAC точно работает?

**Comment by Yexeed** [comment]
Да, все норм без GAC

**Comment by SergeyDertan** [comment]
[Исправил](https://github.com/SergeyDertan/SRegionProtector/commit/4e0ce91e1095a890fa9d2cfca523668ec40ad51d)
