### ISSUE TITLE
I hust install a plugin and it looks something wrong

### ISSUE THREAD

**Issue by SanCoCraft** [SergeyDertan/SRegionProtector#17]
`15:46:12 [INFO ] Loading nukkit.yml ...
15:46:12 [INFO ] Loading server properties ...
15:46:12 [INFO ] 設定 中文(繁體) (cht) 為基本語言
15:46:12 [INFO ] 正在啟動支援 Minecraft: BE v1.12.0 版本的伺服器
15:46:12 [INFO ] Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
15:46:12 [INFO ] 正在啟動伺服器在 0.0.0.0:19132
15:46:12 [INFO ] 此伺服器正在運作 Nukkit git-4c37559 版本 "" (API 1.0.8)
15:46:12 [INFO ] Nukkit 根據 LGPL 許可發行
15:46:13 [INFO ] Loading recipes...
15:46:13 [INFO ] Loaded 1301 recipes.
15:46:13 [INFO ] 成功加載 0 個資源包
15:46:13 [INFO ] 讀取中... SRegionProtector v20.0
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.PlatformDependent0$1 (file:/C:/Users/doesh/Desktop/NukkitX/nukkit-1.0-SNAPSHOT.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.PlatformDependent0$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
15:46:13 [INFO ] 開啟中... SRegionProtector v20.0
15:46:13 [ERROR] Throwing
java.lang.RuntimeException: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:733) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:722) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:483) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) ~[nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at cn.nukkit.plugin.LibraryLoader.load(LibraryLoader.java:73) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.LibraryLoader.load(LibraryLoader.java:33) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.loadLibraries(SRegionProtectorMain.java:332) ~[?:?]
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onEnable(SRegionProtectorMain.java:88) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 4 more
15:46:13 [INFO ] 關閉中... SRegionProtector v20.0
15:46:13 [INFO ] [SRegionProtector] Starting saving...
15:46:13 [ERROR] Throwing
java.lang.NullPointerException: null
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.save(SRegionProtectorMain.java:239) ~[?:?]
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.save(SRegionProtectorMain.java:224) ~[?:?]
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onDisable(SRegionProtectorMain.java:416) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:513) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:445) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:733) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:722) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:483) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) ~[nukkit-1.0-SNAPSHOT.jar:?]
15:46:13 [INFO ] Epoll is unavailable. Reverting to NioEventLoop.
15:46:13 [INFO ] 準備地圖中... "world"
15:46:13 [INFO ] 準備地圖中... "seed"
15:46:13 [INFO ] 準備地圖中... "generator"
15:46:13 [INFO ] 準備地圖中... "nether"
15:46:13 [INFO ] 啟動 GS4 狀態監聽器
15:46:13 [INFO ] 設定 query 介面到 19132
15:46:13 [INFO ] Query 運作在 0.0.0.0:19132
15:46:13 [INFO ] 預設的遊戲類型：生存模式
15:46:13 [INFO ] 讀取完成 (1.367s)！如需幫助，請輸入 "help" 或 "?"
> pl
15:46:24 [INFO ] 插件 (1)：SRegionProtector v20.0
>`

**Comment by SergeyDertan** [comment]
What java version do you have?

**Comment by SanCoCraft** [comment]
Java Jdk12

**Comment by SergeyDertan** [comment]
Try using java 8

**Comment by SanCoCraft** [comment]
WOW,thanks you a lot
XD
