### ISSUE TITLE
SRegionProtector

### ISSUE THREAD

**Issue by jrodr10** [SergeyDertan/SRegionProtector#19]
Simply updated from SRegionProtector 17.8 and this happened. i deleted all files in relation to this plugin so it would reinstall those files. No luck. I've reverted back to 17.8 till further update becomes workable.

20:59:46 [INFO ] Enabling SRegionProtector v20.1
20:59:46 [ERROR] Throwing
java.lang.RuntimeException: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:733) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:722) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:483) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) ~[nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at cn.nukkit.plugin.LibraryLoader.load(LibraryLoader.java:73) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.LibraryLoader.load(LibraryLoader.java:33) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.loadLibraries(SRegionProtectorMain.java:332) ~[?:?]
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onEnable(SRegionProtectorMain.java:88) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 4 more
20:59:46 [INFO ] Disabling SRegionProtector v20.1
20:59:46 [INFO ] [SRegionProtector] Starting saving...
20:59:46 [ERROR] Throwing
java.lang.NullPointerException: null
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.save(SRegionProtectorMain.java:239) ~[?:?]
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.save(SRegionProtectorMain.java:224) ~[?:?]
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onDisable(SRegionProtectorMain.java:416) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:513) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:445) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:733) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:722) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:483) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) ~[nukkit-1.0-SNAPSHOT.jar:?]

**Comment by SergeyDertan** [comment]
Try using java 8

**Comment by jrodr10** [comment]
Why would i downgrade java just to use 1 plugin

**Comment by SergeyDertan** [comment]
https://github.com/NukkitX/Nukkit/issues/912

**Comment by jrodr10** [comment]
Okay
