### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by Bruth78** [SergeyDertan/SRegionProtector#20]
Hello.
Lately, I’ve been trying to setup a region, in which mobs aren’t allowed to spawn, so I turned “mob_spawn” to “deny” unfortunately, mobs keep spawning in that area, most other flags seemed to work so I tried it again by changing the flag to “allow”, didn’t work either.
I’m looking forward to your response, 
~ Leonard.

**Comment by Bruth78** [comment]
also, I've been receiving hella lot of errors too:
18:13:55 [INFO ] [SRegionProtector] Data provider was set to YAML
18:13:55 [ERROR] Throwing
java.lang.RuntimeException: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [server.jar:?]
at cn.nukkit.Server.enablePlugin(Server.java:733) [server.jar:?]
at cn.nukkit.Server.enablePlugins(Server.java:722) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:483) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
at Sergey_Dertan.SRegionProtector.Provider.DataObject.Converter.toDataObject(Converter.java:125) ~[?:?]
at Sergey_Dertan.SRegionProtector.Provider.YAMLDataProvider.loadFlags(YAMLDataProvider.java:91) ~[?:?]
at Sergey_Dertan.SRegionProtector.Region.RegionManager.init(RegionManager.java:66) ~[?:?]
at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.initRegions(SRegionProtectorMain.java:201) ~[?:?]
at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onEnable(SRegionProtectorMain.java:96) ~[?:?]
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[server.jar:?]
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[server.jar:?]
... 4 more
18:13:55 [INFO ] Disabling SRegionProtector v20.2
18:13:55 [INFO ] [SRegionProtector] Starting saving...
18:13:55 [INFO ] [SRegionProtector] Saved 0 regions
18:13:55 [ERROR] Throwing
java.lang.NullPointerException: null
at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.shutdownExecutors(SRegionProtectorMain.java:362) ~[?:?]
at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onDisable(SRegionProtectorMain.java:418) ~[?:?]
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91) ~[server.jar:?]
at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:132) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:513) [server.jar:?]
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:445) [server.jar:?]
at cn.nukkit.Server.enablePlugin(Server.java:733) [server.jar:?]
at cn.nukkit.Server.enablePlugins(Server.java:722) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:483) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]

**Comment by SergeyDertan** [comment]
I'll check.
Send me plugin data folder so I can check the second error

**Comment by Bruth78** [comment]
Honestly, I can’t even find it.
![D88D2337-AC47-49E4-89DB-219E887A109B](https://user-images.githubusercontent.com/46278674/71473733-9554c000-27d8-11ea-830f-3e0203602c49.png)
![2DF2F013-5441-478D-9964-745D80C8237C](https://user-images.githubusercontent.com/46278674/71473734-9554c000-27d8-11ea-9576-d132c938031f.png)
![930CFD1B-275A-479F-A16E-87941AF4DDDB](https://user-images.githubusercontent.com/46278674/71473735-9554c000-27d8-11ea-987b-bc829816e819.jpeg)

**Comment by Bruth78** [comment]
I do have the plugins enabled & have restarted the server but I still can’t find the folder

**Comment by Bruth78** [comment]
Never mind, found it.

**Comment by Bruth78** [comment]
https://pastebin.com/qx2NdgDi

**Comment by SergeyDertan** [comment]
I need u`r regions folder

**Comment by Bruth78** [comment]
[Sergey_Dertan_Plugins.zip](https://github.com/SergeyDertan/SRegionProtector/files/4003221/Sergey_Dertan_Plugins.zip)
Here is all the data I have of your plugin.
Thank you for your help

**Comment by Bruth78** [comment]
@SergeyDertan 
I hope that works too.

**Comment by SergeyDertan** [comment]
[k.zip](https://github.com/SergeyDertan/SRegionProtector/files/4008052/k.zip)
put in flags folder

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/f698c0602a87253fa8bf292b032a0c44698a647b
