### ISSUE TITLE
EntityPortalEnterEvent Error

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SRegionProtector#25]
I think something is wrong with portal.

Server Log: 
16:50:05 [FATAL] "cn.nukkit.event.entity.EntityPortalEnterEvent" 이벤트를 "SRegionProtector v20.3"에 전달할 수 없습니다: Sergey_Dertan.SRegionProtector.Event.RegionEventsHandler에서 의 null
16:50:05 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]                                                                             at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                       at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1275) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                               at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:224) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.onUpdate(Player.java:1688) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.level.Level.doTick(Level.java:820) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.checkTickUpdates(Server.java:1055) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                                    at cn.nukkit.Server.tick(Server.java:1137) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                                                at cn.nukkit.Server.tickProcessor(Server.java:905) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                                        at cn.nukkit.Server.start(Server.java:882) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                                                at cn.nukkit.Server.<init>(Server.java:567) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                                         Caused by: java.lang.IllegalArgumentException: Neither overworld nor nether given!                                                                                                            at cn.nukkit.level.EnumLevel.moveToNether(EnumLevel.java:68) ~[nukkit-1.0-SNAPSHOT.jar:?]                                                                                             at Sergey_Dertan.SRegionProtector.Event.RegionEventsHandler.entityPortalEnter(RegionEventsHandler.java:438) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 12 more
16:50:05 [ERROR] "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.IllegalArgumentException: Neither overworld nor nether given!
        at cn.nukkit.level.EnumLevel.moveToNether(EnumLevel.java:68)
        at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1278)
        at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:224)
        at cn.nukkit.Player.onUpdate(Player.java:1688)
        at cn.nukkit.level.Level.doTick(Level.java:820)
        at cn.nukkit.Server.checkTickUpdates(Server.java:1055)
        at cn.nukkit.Server.tick(Server.java:1137)
        at cn.nukkit.Server.tickProcessor(Server.java:905)
        at cn.nukkit.Server.start(Server.java:882)
        at cn.nukkit.Server.<init>(Server.java:567)
        at cn.nukkit.Nukkit.main(Nukkit.java:112)

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/ac84d954b3494b4fd1f7390905f443a6ea08fdeb
