### ISSUE TITLE
An error caused from sregionprotector plugin

### ISSUE THREAD

**Issue by Saxavlax001** [SergeyDertan/SRegionProtector#4]
09:10:53 [ALERT] java.lang.RuntimeException: java.lang.IllegalArgumentException: Empty string not allowed
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:237)
        at cn.nukkit.level.format.generic.BaseLevelProvider.saveChunks(BaseLevelProvider.java:294)
        at cn.nukkit.level.Level.saveChunks(Level.java:1151)
        at cn.nukkit.level.Level.save(Level.java:1142)
        at cn.nukkit.level.Level.save(Level.java:1125)
        at cn.nukkit.Server.doAutoSave(Server.java:1042)
        at cn.nukkit.Server.tick(Server.java:1110)
        at cn.nukkit.Server.tickProcessor(Server.java:848)
        at cn.nukkit.Server.start(Server.java:825)
        at cn.nukkit.Server.<init>(Server.java:514)
        at cn.nukkit.Nukkit.main(Nukkit.java:109)
Caused by: java.lang.IllegalArgumentException: Empty string not allowed         at cn.nukkit.nbt.tag.StringTag.<init>(StringTag.java:18)
        at cn.nukkit.nbt.tag.CompoundTag.putString(CompoundTag.java:86)         at cn.nukkit.blockentity.BlockEntity.saveNBT(BlockEntity.java:151)
        at Sergey_Dertan.SRegionProtector.BlockEntity.BlockEntityHealer.saveNBT(BlockEntityHealer.java:78)
        at cn.nukkit.level.format.anvil.Chunk.toBinary(Chunk.java:394)
        at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:152)
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:235)
        ... 10 more

**Comment by SergeyDertan** [comment]
can u contact me in discord or telegram?

**Comment by Saxavlax001** [comment]
why?

**Comment by SergeyDertan** [comment]
I need copy of u`r world & regions from SRP/Regions folder

**Comment by SergeyDertan** [comment]
Cant reproduce
