### ISSUE TITLE
error java

### ISSUE THREAD

**Issue by ghost** [SergeyDertan/SRegionProtector#67]
java.lang.RuntimeException: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:408) [Nukkit-PM1E.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:689) [Nukkit-PM1E.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:679) [Nukkit-PM1E.jar:?]
	at cn.nukkit.Server.<init>(Server.java:421) [Nukkit-PM1E.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:78) [Nukkit-PM1E.jar:?]
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at cn.nukkit.plugin.LibraryLoader.load(LibraryLoader.java:70) ~[Nukkit-PM1E.jar:?]
	at cn.nukkit.plugin.LibraryLoader.load(LibraryLoader.java:30) ~[Nukkit-PM1E.jar:?]
	at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.loadLibraries(SRegionProtectorMain.java:337) ~[?:?]
	at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onEnable(SRegionProtectorMain.java:88) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[Nukkit-PM1E.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:119) ~[Nukkit-PM1E.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:404) ~[Nukkit-PM1E.jar:?]
	... 4 more
2021-02-07 22:04:15.423 [main] INFO  - Disabling SRegionProtector v30.0
2021-02-07 22:04:15.435 [main] INFO  - [В§eSRegionProtectorВ§f] В§aStarting saving...
2021-02-07 22:04:15.438 [main] ERROR - Throwing
java.lang.NullPointerException: null
	at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.save(SRegionProtectorMain.java:239) ~[?:?]
	at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.save(SRegionProtectorMain.java:224) ~[?:?]
	at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onDisable(SRegionProtectorMain.java:421) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91) ~[Nukkit-PM1E.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:134) ~[Nukkit-PM1E.jar:?]
	at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:479) [Nukkit-PM1E.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:410) [Nukkit-PM1E.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:689) [Nukkit-PM1E.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:679) [Nukkit-PM1E.jar:?]
	at cn.nukkit.Server.<init>(Server.java:421) [Nukkit-PM1E.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:78) [Nukkit-PM1E.jar:?]

**Comment by SergeyDertan** [comment]
https://github.com/CloudburstMC/Nukkit/issues/912
