### ISSUE TITLE
NukkitPetteriM1Edition Supported

### ISSUE THREAD

**Issue by ghost** [SergeyDertan/SRegionProtector#68]
Сделайте поддержку плагина под ядро https://github.com/PetteriM1/NukkitPetteriM1Edition 

Ошибки которые выдает плагин при запуске >
https://pastebin.com/duFktm2W
https://pastebin.com/Dq0aZ4ir
`[WARN ] [SRegionProtector] java.lang.ArrayIndexOutOfBoundsException: 6756
        at cn.nukkit.block.Block.get(Block.java:394)
        at Sergey_Dertan.SRegionProtector.Settings.Settings.<init>(Settings.java:120)
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.initSettings(SRegionProtectorMain.java:171)
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onEnable(SRegionProtectorMain.java:90)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:119)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:404)
        at cn.nukkit.Server.enablePlugin(Server.java:689)
        at cn.nukkit.Server.enablePlugins(Server.java:679)
        at cn.nukkit.Server.<init>(Server.java:421)
        at cn.nukkit.Nukkit.main(Nukkit.java:78)`

Я так понимаю нужно сделать поддержку что бы можно было указать версию протокола в border-block: "20" например 422:20:2

**Comment by SergeyDertan** [comment]
то что по ссылке на пастебине ошибка связання с загрузчиком библиотек на версии джавы больше 8
связано это с багом ядра и к самому плагину отношения не имеет

**Comment by SergeyDertan** [comment]
второе можно поправить, но к сожалению времени нет

**Comment by ghost** [comment]
Please fix supported core NukkitPetteriM1Edition
