### ISSUE TITLE
PlaceholderAPI 1.4 update

### ISSUE THREAD

**Issue by ghost** [SergeyDertan/SRegionProtector#70]
Обновите ваш плагин до PlaceholderAPI 1.4

```
[main] ERROR - Throwing
java.lang.RuntimeException: java.lang.IncompatibleClassChangeError: Found class com.creeperface.nukkit.placeholderapi.api.PlaceholderAPI, but interface was expected
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:408) [Nukkit-PM1E.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:692) [Nukkit-PM1E.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:682) [Nukkit-PM1E.jar:?]
	at cn.nukkit.Server.<init>(Server.java:424) [Nukkit-PM1E.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:77) [Nukkit-PM1E.jar:?]
Caused by: java.lang.IncompatibleClassChangeError: Found class com.creeperface.nukkit.placeholderapi.api.PlaceholderAPI, but interface was expected
	at Sergey_Dertan.SRegionProtector.Utils.PlaceholdersLoader.<clinit>(PlaceholdersLoader.java:16) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_275]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_275]
	at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.registerPlaceholders(SRegionProtectorMain.java:379) ~[?:?]
	at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onEnable(SRegionProtectorMain.java:114) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[Nukkit-PM1E.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:119) ~[Nukkit-PM1E.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:404) ~[Nukkit-PM1E.jar:?]
	... 4 more
```

**Comment by mercadanteus** [comment]
Please fix this error, I think is same as my report

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/65c9563d471551482e8a738f166ea58e6310d692
