### ISSUE TITLE
Ошибка запуска плагина. Eror start plugin

### ISSUE THREAD

**Issue by IllyaVasilev1** [SergeyDertan/SRegionProtector#71]
`Включение SRegionProtector v30.0
2021-05-08 16:03:21.847 [main] FATAL - An error occurred while enabling the plugin SRegionProtector, 30.0, Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at cn.nukkit.plugin.LibraryLoader.load(LibraryLoader.java:73) ~[minecraft.jar:?]
	at cn.nukkit.plugin.LibraryLoader.load(LibraryLoader.java:33) ~[minecraft.jar:?]
	at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.loadLibraries(SRegionProtectorMain.java:337) ~[?:?]
	at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onEnable(SRegionProtectorMain.java:88) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:101) ~[minecraft.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120) ~[minecraft.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:459) [minecraft.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:937) [minecraft.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:926) [minecraft.jar:?]
	at cn.nukkit.Server.<init>(Server.java:685) [minecraft.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:194) [minecraft.jar:?]
2021-05-08 16:03:21.859 [main] INFO  - Выключение SRegionProtector v30.0
2021-05-08 16:03:21.860 [main] INFO  - [§eSRegionProtector§f]: §aЗапуск сохранения...
2021-05-08 16:03:21.861 [main] FATAL - An error occurred while disabling the plugin SRegionProtector, 30.0, Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain
java.lang.NullPointerException: null
	at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.save(SRegionProtectorMain.java:239) ~[?:?]
	at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.save(SRegionProtectorMain.java:224) ~[?:?]
	at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onDisable(SRegionProtectorMain.java:421) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:103) ~[minecraft.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:140) ~[minecraft.jar:?]
	at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:539) [minecraft.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:463) [minecraft.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:937) [minecraft.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:926) [minecraft.jar:?]
	at cn.nukkit.Server.<init>(Server.java:685) [minecraft.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:194) [minecraft.jar:?]
`

**Comment by SergeyDertan** [comment]
Это баг ядра
Я давно писал им, но толку нет
Работает только с джавой 8
