### ISSUE TITLE
Latest Nukkit Throwing Error

### ISSUE THREAD

**Issue by rackgaming** [SergeyDertan/SRegionProtector#74]
`Throwing
java.lang.NullPointerException: Cannot invoke "Sergey_Dertan.SRegionProtector.Region.RegionManager.save(Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain$SaveType, String)" because "this.regionManager" is null
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.save(SRegionProtectorMain.java:239) ~[?:?]
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.save(SRegionProtectorMain.java:224) ~[?:?]
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onDisable(SRegionProtectorMain.java:421) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91) ~[server.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:132) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:510) [server.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:442) [server.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:750) [server.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:739) [server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:507) [server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]`

**Comment by rackgaming** [comment]
`[ERROR] Throwing
java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @2a48d10f
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [server.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:750) [server.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:739) [server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:507) [server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @2a48d10f
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at cn.nukkit.plugin.LibraryLoader.load(LibraryLoader.java:71) ~[server.jar:?]
        at cn.nukkit.plugin.LibraryLoader.load(LibraryLoader.java:33) ~[server.jar:?]
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.loadLibraries(SRegionProtectorMain.java:337) ~[?:?]
        at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onEnable(SRegionProtectorMain.java:88) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[server.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[server.jar:?]
        ... 4 more`

**Comment by SergeyDertan** [comment]
Hello
Unfortunately I have no time to fix it

**Comment by rackgaming** [comment]
Like right now or just in general? Im in no rush.

**Comment by SergeyDertan** [comment]
In general

**Comment by twixi** [comment]
help too

**Comment by twixi** [comment]
need to update to java11
